apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
      - name: api-pvc
        persistentVolumeClaim:
          claimName: api-pvc
      containers:
      - name: api
        image: api
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SQLITE_DB_PATH
          value: /data/api.db
        volumeMounts:
        - mountPath: /data
          name: api-pvc
