---
apiVersion: batch/v1
kind: Job
metadata:
  name: webdb-migration
  namespace: web
  labels:
    app: web
spec:
  template:
    metadata:
      labels:
        app: web
    spec:
      restartPolicy: OnFailure
      volumes:
      - name: web-pvc
        persistentVolumeClaim:
          claimName: web-pvc
      containers:
      - name: migrations
        image: migrations
        imagePullPolicy: Never
        volumeMounts:
        - mountPath: /data
          name: web-pvc
  backoffLimit: 4
