apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
      - name: web-pvc
        persistentVolumeClaim:
          claimName: web-pvc
      containers:
      - name: web
        image: web
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SQLITE_DB_PATH
          value: /data/web.db
        volumeMounts:
        - mountPath: /data
          name: web-pvc
