---
apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      volumes:
      - name: api-pvc
        persistentVolumeClaim:
          claimName: api-pvc
      containers:
      - name: api
        image: api
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SQLITE_DB_PATH
          value: /data/api.db
        volumeMounts:
        - mountPath: /data
          name: api-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pvc
  namespace: api
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
