apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  template:
    spec:
      containers:
        - name: web
          env:
          - name: GIN_MODE
            value: release
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret-key
                key: SECRET_KEY
