apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: web
patches:
- path: deployment-patch.yaml
  target:
    kind: Deployment
secretGenerator:
- name: jwt-secret-key
  envs:
  - .secret.env
